### PR TITLE
Updated student list as much as I could

### PR DESCRIPTION
**Pull request by drichmond**
* Used LinkedIn pages for Alumni

### CODE REVIEW

**Comment by sbeamer** [comment]
There is another page for alumni. Should we put the links there, or merge alumni into the student page?

**Comment by drichmond** [comment]
Either way works. I didn't realize there was an alumni page so I just updated this one.

**Comment by drichmond** [comment]
I'll merge my changes to the alumni page

**Comment by sbeamer** [comment]
I merged it in crudely. We should probably think about what data we want per entry, how to format it, and then apply it consistently across all.

**Pull request merged**
